import type {Metadata} from "next";
import "./globals.css";
// import {Button} from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Ciudadania",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="full-w px-10  antialiased">
        <header className="flex flex-row justify-between  p-4 ">
          <a href="/">
            <h1 className="text-2xl font-bold">Ciudadania Italiana</h1>
          </a>
        </header>
        <main className="mx-auto max-w-4xl p-4">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} Ciudadania
        </footer>
      </body>
    </html>
  );
}
