import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ciudadania",
  description: "Generated by appncy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="es">
      <body className="flex gap-4 full-w min-h-screen px-10 antialiased">
        <header className="flex p-4">
          <a href="/">
            <h1 className="text-2xl font-bold">Ciudadania Italiana</h1>
          </a>
        </header>

        <main className="flex-1 mx-auto max-w-4xl">{children}</main>

        <footer>
          <p className="text-center leading-[4rem] opacity-70">
            © {new Date().getFullYear()} Ciudadania
          </p>
        </footer>
      </body>
    </html>
  );
}
